version: "3.8"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: illuvcoffee
      POSTGRES_PASSWORD: 1lluvC0ff33&C0d!n5
      POSTGRES_DB: illuvcoffee_db
